export interface Event {
  readonly eventName: string;
  readonly addressOfEvent: string;
  readonly addressLatitude: string;
  readonly addressLongitude: string;
  readonly exactDate: string;
  readonly startTime: string;
  readonly finishTime: string
  readonly eventStartInterval: string;
  readonly eventFinishInterval: string;
  readonly citizenName: string;
  readonly citizenPhoto: string;
  readonly companyName: string;
  readonly companyLogo: string;
  readonly telNumberPrime: number;
  readonly usersEmail: string;
  readonly sitePrime: string;
  readonly aboutEvent: string;
  readonly personToContact: string;
  readonly placePicture: string;
  readonly meetingPlace: string;
  readonly meetingPlaceLatitude: string;
  readonly meetingPlaceLongitude: string;
  readonly getToPlace: string;
  readonly whatToDo: string;
  readonly equipment: string;
  readonly minPeople: number;
  readonly maxPeople: number;
  readonly smthElse: string;
}